services:
  bot:
    build: .
    container_name: actual_expense_logger
    restart: unless-stopped
    env_file:
      - .env
    environment:
      - ACTUAL_DATA_DIR=/app/data
    volumes:
      - actual_bot_data:/app/data
    secrets:
      - telegram_bot_token
      - actual_password
      - actual_file_password

volumes:
  actual_bot_data:
    name: actual_bot_data

secrets:
  telegram_bot_token:
    file: ./secrets/telegram_bot_token.txt
  actual_password:
    file: ./secrets/actual_password.txt
  actual_file_password:
    file: ./secrets/actual_file_password.txt
